- name: ensure some base packages are installed
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - wget
    - curl
    - git

- name: ensure user `vagrant` is part of `vboxsf` group (to access shared folder)
  user: name=vagrant groups=vboxsf append=yes
